version: "3.7"

services:
    web:
        container_name: "web"
        build: ./Web
        volumes:
            - ./Web/src:/var/www/html
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
            - 443

    maria:
        build: dataBase
        volumes:
            - dataBase:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "3111997"
        ports:
            - 3306:3306

volumes: 
    dataBase:
        driver: local
